from .style import SKY_TYPE_COLORS, CLOUD_PROP_COLORS, STATION_COLORS, DEFAULT_ALPHA, DEFAULT_LINESTYLE
from .style import set_paper_style, SIMULATION_COLOR, SIMULATION_LS, SIMULATION_M, OBSERVATION_COLOR, OBSERVATION_LS, OBSERVATION_M

STATIONS = {
    "Florida": (60.3833, 5.3333),         # (lat, lon)
    "Flesland": (60.292792, 5.222689)
}